CREATE TABLE Cliente(
	IdCliente INT PRIMARY KEY IDENTITY(1,1),
	NomeCliente VARCHAR(60) UNIQUE NOT NULL,
	Sexo CHAR(1) NOT NULL, 
	DataNascimento DATE NOT NULL,
	Ativo BIT NOT NULL	
)


CREATE TABLE TipoProduto(
	IdTipoProduto SMALLINT PRIMARY KEY IDENTITY(1,1),
	NomeTipoProduto VARCHAR(30) UNIQUE NOT NULL
)

CREATE TABLE Marca(
	IdMarca SMALLINT PRIMARY KEY IDENTITY(1,1),
	NomeMarca VARCHAR(30) UNIQUE NOT NULL
)

CREATE TABLE Produto(
	IdProduto INT PRIMARY KEY IDENTITY(1,1),
	IdTipoProduto SMALLINT FOREIGN KEY REFERENCES TipoProduto(IdTipoProduto) NOT NULL,
	IdMarca SMALLINT FOREIGN KEY REFERENCES Marca(IdMarca) NOT NULL,
	NomeProduto VARCHAR(50) UNIQUE NOT NULL,
	ValorCompra DECIMAL(4,2) NOT NULL,
	ValorVenda DECIMAL(4,2) NOT NULL,
	QuantidadeEstoque INT NOT NULL,
)


CREATE TABLE Venda(
	IdVenda INT PRIMARY KEY IDENTITY(1,1),
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente) NOT NULL,
	DataVenda DATETIME DEFAULT GETDATE(),
	DataPagamento DATETIME,
)

CREATE TABLE VendaItem(
	IdVendaItem INT PRIMARY KEY IDENTITY(1,1),
	IdVenda INT FOREIGN KEY REFERENCES Venda(IdVenda) NOT NULL,
	IdProduto INT FOREIGN KEY REFERENCES Produto(IdProduto) NOT NULL,
	Quantidade SMALLINT NOT NULL
)